name: 🚀 Auto-release DEB Package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Build DEB package
        run: |
          mkdir -p pkg/usr/local/bin
          mkdir -p pkg/DEBIAN
          cp create-repo pkg/usr/local/bin/
          cp update-all.sh pkg/usr/local/bin/
          chmod +x pkg/usr/local/bin/*
          echo "Package: create-repo-auto" > pkg/DEBIAN/control
          echo "Version: ${GITHUB_REF#refs/tags/v}" >> pkg/DEBIAN/control
          echo "Architecture: all" >> pkg/DEBIAN/control
          echo "Maintainer: justrunme <you@example.com>" >> pkg/DEBIAN/control
          echo "Description: Auto-create and sync repos for GitHub/GitLab" >> pkg/DEBIAN/control
          dpkg-deb --build pkg create-repo-auto_${GITHUB_REF#refs/tags/v}.deb

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: '*.deb'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
