name: Build and Release DEB Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Prepare package structure
        run: |
          mkdir -p pkg/usr/local/bin
          mkdir -p pkg/DEBIAN
          cp create-repo pkg/usr/local/bin/
          cp update-all.sh pkg/usr/local/bin/
          chmod +x pkg/usr/local/bin/*
          echo "Package: create-repo-auto" > pkg/DEBIAN/control
          echo "Version: ${GITHUB_REF#refs/tags/v}" >> pkg/DEBIAN/control
          echo "Architecture: all" >> pkg/DEBIAN/control
          echo "Maintainer: justrunme <you@example.com>" >> pkg/DEBIAN/control
          echo "Description: Auto-create repo and auto-sync with GitHub/GitLab" >> pkg/DEBIAN/control

      - name: Build DEB package
        run: |
          dpkg-deb --build pkg create-repo-auto_${GITHUB_REF#refs/tags/v}.deb

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: 'create-repo-auto_*.deb'
