name: Build and Release DEB Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Build DEB
        run: |
          dpkg-deb --build . create-repo-auto_${GITHUB_REF#refs/tags/v}.deb

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
